# **2020 NIPA 인공지능/데이터분석 믹스앤매치 아카데미**
- python/pandas 주요 개념 점검

# 기본 python 활용(1)

In [ ]:
# print()를 사용하면 원하는 내용 출력이 가능
print('hello')

hello

In [ ]:
# 간단한 숫자 계산도 가능
print(1 + 3)

4

In [ ]:
# 변수에 데이터를 저장하여 활용이 가능
a = 'hello, elice!'
print(a)

hello, elice!

In [ ]:
# 변수에 새로운 값을 덮어씌울 수 있음
print(a)
a = 'good morning'
print(a)

hello, elice!
good morning

In [ ]:
# 변수를 활용한 계산이 가능
a = 2
b = 5
print(a * b)

10

In [ ]:
# 변수는 여러 개를 조합하여 사용이 가능
print(a + b + 15 + b - 7)

20

In [ ]:
# []를 사용하면 여러 데이터 값을 한 번에 저장이 가능 -> 리스트
my_list = ['apple', 'banana', 'orange', 'grape']
print(my_list)

['apple', 'banana', 'orange', 'grape']

In [ ]:
# list.append()를 사용하면 원하는 값 하나를 추가할 수 있음
my_list.append('pineapple')
print(my_list)

['apple', 'banana', 'orange', 'grape', 'pineapple']

In [ ]:
# remove()를 사용하면 리스트에서 값 하나를 삭제할 수 있음
my_list.remove('pineapple')
print(my_list)

['apple', 'banana', 'orange', 'grape']

In [ ]:
# 숫자 자료형은 연산이 가능
print(1987 + 20)

2007

In [ ]:
# 텍스트 자료형은 숫자 연산이 불가능
print('1987' + 20)

TypeError: ignored

In [ ]:
# 대신 텍스트 자료형끼리는 합하여 한 번에 출력할 수 있다
print('hello ' + 'world!')

# 기본 python 활용(2) - 반복문

In [ ]:
# 반복문에 사용할 리스트 확인
print(my_list)

['apple', 'banana', 'orange', 'grape']

In [ ]:
# for문을 사용하면 리스트 안에 있는 값을 순서대로 꺼내올 수 있음
for fruit in my_list:
  print(fruit)

apple
banana
orange
grape

In [ ]:
# range(start, end)는 시작 숫자부터 끝 전 숫자까지 이어주는 값을 만들어주는 특별한 함수
print(range(0, 10))
# print(list(range(0, 10))) # list()로 감싸서 보면 list 형태로 값을 볼 수 있다

range(0, 10)

In [ ]:
# for 반복문과 range 함수는 자주 사용되는 조합
for i in range(0, 30):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29

In [ ]:
# 활용 사례 2
for i in range(0, 5):
  print('안녕하세요')

안녕하세요
안녕하세요
안녕하세요
안녕하세요
안녕하세요

# 3. 기본 python 활용(3) - 조건문

In [ ]:
# if else 문을 사용하면 조건문 사용이 가능
# 조건에 맞는 위치에 있는 코드만 실행이 된다
a = 10
if a < 5:
  print('조건이 참일 경우에 실행되는 문장')
else:
  print('조건이 거짓일 경우에 실행되는 문장')

조건이 거짓일 경우에 실행되는 문장

In [ ]:
# if else 문 활용 예제
a = 10
if a > 5:
  print('조건이 참일 경우에 실행되는 문장')
else:
  print('조건이 거짓일 경우에 실행되는 문장')

조건이 참일 경우에 실행되는 문장

In [ ]:
# 두 조건이 같다는 것을 표시해 줄 때는 ==을 사용
# test 변수의 값을 변경해가며 '정답입니다'를 출력해보자 
test = 50
if test == 30:
  print('정답입니다')  # else문이 필요 없다면 생략이 가능

In [ ]:
# elif문을 사용하면 추가 조건 지정이 가능하다
my_fruit = 'banana'
if my_fruit == 'apple':
  print('맛있는 사과')
elif my_fruit == 'banana':
  print('맛있는 바나나')
else:
  print('무슨 과일인가요?')

맛있는 바나나

In [ ]:
# for문과 반복문은 중첩해서 사용이 가능하다
my_list = ['apple', 'banana', 'orange', 'grape']
for fruit in my_list:
  if fruit != 'banana':   # != 는 두 변수가 서로 같지 않다는 것을 지칭
    print(fruit + ' 좋아!')
  else:
    print(fruit + ' 싫어!')

apple 좋아!
banana 싫어!
orange 좋아!
grape 좋아!

# 4. pandas 기본(1)

In [ ]:
# import를 사용하면 사전 설치된 라이브러리를 불러올 수 있음
# 라이브러리는 일종의 확장팩 같은 개념으로, 수많은 라이브러리들이 존재하며 사용자들은 단지 불러오는 것 만으로 그 기능들을 사용 가능
import pandas

In [ ]:
# pandas.기능()과 같이 pandas 라이브러리의 추가 기능을 사용할 수 있음
pandas.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [ ]:
# 라이브러리를 불러올 때 as 를 주면 앨리어스(단축어) 옵션을 줄 수 있음
import pandas as pd
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [ ]:
# pandas는 python의 대표적인 데이터 분석 라이브러리
# pandas를 활용하면 데이터를 자유자재로 처리 및 분석이 가능

# pd.DataFrame()은 데이터프레임을 만드는 명령어 -> 데이터프레임은 pandas의 기본 구조
pd.DataFrame([1, 2, 3]) # 리스트 형태로 데이터를 넣는다

   0
0  1
1  2
2  3

In [ ]:
# 리스트 안의 리스트를 넣어 리스트 중첩 구조로 표현이 가능
nest_list = [[1, 2], [3, 4], [5, 6]]
print(nest_list)

[[1, 2], [3, 4], [5, 6]]

In [ ]:
# 리스트가 이중 중첩된 상태 -> 2차원 데이터 구조
# 2차원 데이터 구조는 우리가 흔히 보는 표(테이블) 형태의 데이터
pd.DataFrame(nest_list)

   0  1
0  1  2
1  3  4
2  5  6

In [ ]:
# list를 활용하면 자유자재로 2차원 데이터 표현이 가능
pd.DataFrame([['홍길동', 80, 70, 80],
              ['박철수', 60, 70, 80],
              ['김영희', 70, 90, 80]])

     0   1   2   3
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [ ]:
# 데이터프레임도 변수로 저장이 가능
df = pd.DataFrame([['홍길동', 80, 70, 80],
                   ['박철수', 60, 70, 80],
                   ['김영희', 70, 90, 80]])
df

     0   1   2   3
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [ ]:
# pd.DataFrame() 안에 변수로 데이터를 넣어도 당연히 가능
student_data = [['홍길동', 80, 70, 80],
                ['박철수', 60, 70, 80],
                ['김영희', 70, 90, 80]]
df = pd.DataFrame(student_data)
df

     0   1   2   3
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [ ]:
# columns 옵션을 주면 열(칼럼) 이름을 지정하여 생성이 가능
df = pd.DataFrame(student_data, columns=['이름', '국어', '수학', '영어'])
df

    이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

# 5. pandas 기본(2)

In [ ]:
# <데이터프레임[열 이름]> 을 사용하면 특정 열(칼럼)을 추출(조회)할 수 있다
df['국어']

0    80
1    60
2    70
Name: 국어, dtype: int64

In [ ]:
# 영어 칼럼 조회
df['영어']

0    80
1    80
2    80
Name: 영어, dtype: int64

In [ ]:
# for문 등과 조합이 가능하다
for kor_score in df['국어']:
  print(kor_score)

80
60
70

In [ ]:
# 없는 칼럼을 조회하려 하면 문제가 발생한다
df['사회']

KeyError: ignored

In [ ]:
# 단, 없는 칼럼이라도 편의상 다음 처럼 값을 지정해주면, 해당 값으로 칼럼이 추가된다.
df['사회'] = [50, 60, 60]
df

    이름  국어  수학  영어  사회
0  홍길동  80  70  80  50
1  박철수  60  70  80  60
2  김영희  70  90  80  60

In [ ]:
# 칼럼 삭제는 다음과 같이 사용한다

# df = df.drop()과 같이 삭제 시 df를 새롭게 변경 선언을 해주어야 한다
# (inplace=True도 가능하지만, pandas에서 공식적으로 추천하지 않는 기능이다)

# axis=1을 넣어주어야 함에 주의. axis=1을 넣지 않으면 '행 삭제' 기능이다
df = df.drop('사회', axis=1)
df

    이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [ ]:
# df.loc[행, 열] 명령어를 사용하면 특정 데이터만 추출이 가능
df.loc[1, '이름']

'박철수'

In [ ]:
# 실습
df.loc[2, '수학']

90

In [ ]:
# .loc 메서드를 사용하면 바로 데이터 변경이 가능하다
df.loc[1, '영어'] = 100
df

    이름  국어  수학   영어
0  홍길동  80  70   80
1  박철수  60  70  100
2  김영희  70  90   80

In [ ]:
# 조건에 맞는 데이터만 추출이 가능
df[df['국어']>=70]

    이름  국어  수학  영어
0  홍길동  80  70  80
2  김영희  70  90  80

In [ ]:
# 다음과 같은 형태로 여러 조건을 조합해 사용이 가능하다
# 국어 점수가 70점이고, 수학 점수가 80이 넘는 데이터만 추출
df[(df['국어']==70) & (df['수학']>80)]

    이름  국어  수학  영어
2  김영희  70  90  80

In [ ]:
# set_index(칼럼명)를 사용하면 특정 칼럼을 행 인덱스로 적용 가능
df = df.set_index('이름')
df

     국어  수학   영어
이름
홍길동  80  70   80
박철수  60  70  100
김영희  70  90   80

In [ ]:
# 별도 행 인덱스가 있다면 df.loc를 조금 더 직관적으로 사용이 가능
df.loc['홍길동', '수학']

70

In [ ]:
# df.sum()을 사용하면 열 방향으로 합계를 계산
df.sum()

국어    210
수학    230
영어    260
dtype: int64

In [ ]:
# df.sum(axis=1)을 주면 행 방향으로 합계를 계산
df.sum(axis=1)

이름
홍길동    230
박철수    230
김영희    240
dtype: int64

In [ ]:
# 다음과 같은 응용이 가능하다
df['합계'] = df.sum(axis=1)
df

     국어  수학   영어   합계
이름
홍길동  80  70   80  230
박철수  60  70  100  230
김영희  70  90   80  240

# 6. pandas 기본(3)

In [ ]:
# google colab에서 파일을 업로드해서 저장하는 기능
from google.colab import files
iris_data = files.upload()

# 실제 환경에서는 대부분 이런 식으로 미리 제작된 데이터를 불러와 사용한다
iris = pd.read_csv('iris_data.csv')
iris

KeyboardInterrupt: ignored

     sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
# .shape를 사용하면 데이터의 전체적인 형태를 살펴볼 수 있다
iris.shape

(150, 4)

In [ ]:
# .describe() 메서드를 사용하면 데이터의 전체적인 기술통계량을 한 번에 살펴볼 수 있다
iris.describe()

       sepal length  sepal width  petal length  petal width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
# 첫 5째 행만 살펴보기
# head() 안에 값을 입력하면 보고자 하는 행 크기를 지정할 수 있다(.head(10) -> 첫 10번째 행까지 조회)
iris.head()

   sepal length  sepal width  petal length  petal width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [ ]:
# 마지막 5번째 행만 살펴보기
# 분석해야할 데이터가 큰 경우 이런 식으로 데이터의 전체적인 형태를 살펴보아야 한다
iris.tail()

     sepal length  sepal width  petal length  petal width
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

In [ ]:
# iris 꽃의 꽃받침(sepal) 길이 살펴보기
iris['sepal length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length, Length: 150, dtype: float64

In [ ]:
# 칼럼별(정확히는 Series)로 일괄 계산도 가능하다
iris['sepal length'] / iris['petal length']

0      3.642857
1      3.500000
2      3.615385
3      3.066667
4      3.571429
         ...
145    1.288462
146    1.260000
147    1.250000
148    1.148148
149    1.156863
Length: 150, dtype: float64

In [ ]:
# 다음과 같은 응용도 가능
iris['sepal/petal'] = iris['sepal length'] / iris['petal length']
iris

     sepal length  sepal width  petal length  petal width  sepal/petal
0             5.1          3.5           1.4          0.2     3.642857
1             4.9          3.0           1.4          0.2     3.500000
2             4.7          3.2           1.3          0.2     3.615385
3             4.6          3.1           1.5          0.2     3.066667
4             5.0          3.6           1.4          0.2     3.571429
..            ...          ...           ...          ...          ...
145           6.7          3.0           5.2          2.3     1.288462
146           6.3          2.5           5.0          1.9     1.260000
147           6.5          3.0           5.2          2.0     1.250000
148           6.2          3.4           5.4          2.3     1.148148
149           5.9          3.0           5.1          1.8     1.156863

[150 rows x 5 columns]

In [ ]:
# 조건부 추출 예제
# sepal length가 5보다 큰 데이터만 추출
iris[iris['sepal length'] > 5]

     sepal length  sepal width  petal length  petal width  sepal/petal
0             5.1          3.5           1.4          0.2     3.642857
5             5.4          3.9           1.7          0.4     3.176471
10            5.4          3.7           1.5          0.2     3.600000
14            5.8          4.0           1.2          0.2     4.833333
15            5.7          4.4           1.5          0.4     3.800000
..            ...          ...           ...          ...          ...
145           6.7          3.0           5.2          2.3     1.288462
146           6.3          2.5           5.0          1.9     1.260000
147           6.5          3.0           5.2          2.0     1.250000
148           6.2          3.4           5.4          2.3     1.148148
149           5.9          3.0           5.1          1.8     1.156863

[118 rows x 5 columns]

In [ ]:
# sepal length가 5보다 크거나, petal(꽃잎) length 가 1.5보다 작은 데이터만 추출 (OR 연산)
iris[(iris['sepal length'] > 5) | (iris['petal length'] < 1.5)]

     sepal length  sepal width  petal length  petal width  sepal/petal
0             5.1          3.5           1.4          0.2     3.642857
1             4.9          3.0           1.4          0.2     3.500000
2             4.7          3.2           1.3          0.2     3.615385
4             5.0          3.6           1.4          0.2     3.571429
5             5.4          3.9           1.7          0.4     3.176471
..            ...          ...           ...          ...          ...
145           6.7          3.0           5.2          2.3     1.288462
146           6.3          2.5           5.0          1.9     1.260000
147           6.5          3.0           5.2          2.0     1.250000
148           6.2          3.4           5.4          2.3     1.148148
149           5.9          3.0           5.1          1.8     1.156863

[135 rows x 5 columns]

In [ ]:
# sepal length가 5보다 크면서 petal length 가 1.5보다 작은 데이터만 추출 (AND 연산)
iris[(iris['sepal length'] > 5) & (iris['petal length'] < 1.5)]

    sepal length  sepal width  petal length  petal width  sepal/petal
0            5.1          3.5           1.4          0.2     3.642857
14           5.8          4.0           1.2          0.2     4.833333
16           5.4          3.9           1.3          0.4     4.153846
17           5.1          3.5           1.4          0.3     3.642857
28           5.2          3.4           1.4          0.2     3.714286
33           5.5          4.2           1.4          0.2     3.928571
36           5.5          3.5           1.3          0.2     4.230769